version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}

  web:
    build: ./app
    volumes:
     - ./app:/usr/src/app
     - /usr/src/www:/usr/src/www
    environment:
      DJANGO_ENV_SECRET_KEY: ${DJANGO_ENV_SECRET_KEY}
      DJANGO_ENV_EMAIL_HOST: ${DJANGO_ENV_EMAIL_HOST}
      DJANGO_ENV_EMAIL_PORT: ${DJANGO_ENV_EMAIL_PORT}
      DJANGO_ENV_EMAIL_HOST_USER: ${DJANGO_ENV_EMAIL_HOST_USER}
      DJANGO_ENV_EMAIL_HOST_PASSWORD: ${DJANGO_ENV_EMAIL_HOST_PASSWORD}
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}  
    command: gunicorn --bind 0.0.0.0:8000 django3byexample.wsgi  # python manage.py collectstatic
    expose:
      - 8000
    depends_on:
      - db

  nginx:
     build: ./nginx
     volumes:      
      - /usr/src/www:/usr/src/www
      - /usr/src/www/log/nginx:/var/log/nginx
     ports:
      - 80:80
     depends_on:
      - web
  
# volumes:
# static_volume:
