version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
    user: postgres

  web:
    build: ./app
    volumes:
     - ./app:/usr/src/app  
     - /usr/src/www:/usr/src/www
     - /var/log/gunicorn:/var/log/gunicorn
     - /var/log/django:/var/log/django
    environment:
      DJANGO_ENV_SECRET_KEY: ${DJANGO_ENV_SECRET_KEY}
      DJANGO_ENV_EMAIL_HOST: ${DJANGO_ENV_EMAIL_HOST}
      DJANGO_ENV_EMAIL_PORT: ${DJANGO_ENV_EMAIL_PORT}
      DJANGO_ENV_EMAIL_HOST_USER: ${DJANGO_ENV_EMAIL_HOST_USER}
      DJANGO_ENV_EMAIL_HOST_PASSWORD: ${DJANGO_ENV_EMAIL_HOST_PASSWORD}
      DJANGO_ENV_LOG_PATH: ${DJANGO_ENV_LOG_PATH}
      DJANGO_ENV_WWW_PATH: ${DJANGO_ENV_WWW_PATH}
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}  
    command: gunicorn django3byexample.wsgi -c ./config/gunicorn/gunicorn.conf.py  # python manage.py collectstatic
    expose:
      - 8000
    depends_on:
      - db

  nginx:
     build: ./nginx
     volumes:      
      - /usr/src/www:/usr/src/www
      - /var/log/nginx:/var/log/nginx
      - /etc/nginx/ssl:/etc/nginx/ssl 
     ports:
      - 80:80
      - 443:443
     depends_on:
      - web
  
# volumes:
# static_volume:
